id: I47A3BC98
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:34:54+00:00'
last_modified: '2022-06-07T16:16:05.691536+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20856
  title: བཀའ་ཆེམས་ཀ་ཁོལ་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0BE5:
      image_group_id: I4778
      title: ''
      total_pages: 340
      order: 1
      base_file: 0BE5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
