id: P002928
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20856
  title: བཀའ་ཆེམས་ཀ་ཁོལ་མ
  author: ''
  volumes:
    07e207f485e8414f95ebc0f721322014:
      image_group_id: I4778
      title: ''
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
